apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    httpMethod: GET
- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo
  jsonData:
    httpMethod: GET
    serviceMap:
      datasourceUid: prometheus
- name: Loki
  type: loki
  access: proxy
  uid: loki
  url: http://loki:3100
  jsonData:
     httpHeaderName1: "X-Scope-OrgID"
  secureJsonData:
     httpHeaderValue1: "tenant1"
- name: Mimir
  type: prometheus
  access: proxy
  uid: mimir
  url: http://mimir:9009/prometheus
  jsonData:
    exemplarTraceIdDestinations:
      - datasourceUid: tempo
        name: traceID
    httpMethod: POST
    timeInterval: "2s"
- name: Mimir Alertmanager
  type: alertmanager
  access: proxy
  uid: alertmanager
  url: http://mimir:9009/
  editable: false
  jsonData:
    exemplarTraceIdDestinations:
      httpHeaderName1: "X-Scope-OrgID"
      implementation: "anonymus"
    timeInterval: "2s"