# route:
#   group_by: ['alertname']
#   group_wait: 30s
#   group_interval: 5m
#   repeat_interval: 1h
#   receiver: 'sns-notification'
# receivers:
#   - name: 'sns-notification'
#     sns_configs:
#       - topic_arn: 'arn:aws:sns:us-west-2::email'
#         api_url: https://sns.us-west-2.amazonaws.com  
#         # subject: 'tttt'
#         # message: 'ffff'
#         sigv4:
#           region: 'us-west-2'
#           access_key: ''
#           secret_key: ''
#           profile: 'arn:aws:iam:::user/grafana'
#           # [ role_arn: <string> ]
#         attributes:
#           key: 'somekey'
#           value: 'somevalue'          


# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     equal: ['alertname', 'dev', 'instance']

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: webhook-receiver

receivers:
  # In this example we're not going to send any notification out of Alertmanager.
  - name: 'webhook-receiver'
    webhook_configs:
      - url: 'https://webhook.com'

# # Global settings
# global:
#   resolve_timeout: 5m  # Maximum time to wait for an alert to resolve

# # Routing configuration
# route:
#   group_by: ['alertname']  # Group alerts by their name
#   group_wait: 30s          # Wait time before grouping alerts
#   group_interval: 5m       # Interval for grouping alerts
#   repeat_interval: 1h      # Interval for repeating notifications
#   receiver: 'webhook-receiver'  # Default receiver for alerts

# # Receiver configuration
# receivers:
#   - name: 'webhook-receiver'
#     webhook_configs:
#       - url: 'https://your-webhook-endpoint.com'  # Replace with your actual webhook URL
#         send_resolved: true  # Send resolved alerts as well

# # Inhibition rules
# inhibit_rules:
#   - source_match:
#       alertname: 'HighCPUUsage'  # Suppress related alerts while this one is active
#     target_match_re:
#       alertname: '.*'  # Match any other alert name

# # Additional route for the specific alert
# route:
#   routes:
#     - match:
#         alertname: 'HighCPUUsage'  # Match alerts with this name
#       receiver: 'webhook-receiver'  # Send to the webhook receiver
#       continue: true  # Continue processing other routes