# route:
#   group_by: ['alertname']
#   group_wait: 30s
#   group_interval: 5m
#   repeat_interval: 1h
#   receiver: 'sns-notification'
# receivers:
#   - name: 'sns-notification'
#     sns_configs:
#       - topic_arn: 'arn:aws:sns:us-west-2:529347085383:testingemail'
#         api_url: https://sns.us-west-2.amazonaws.com  
#         # subject: 'tttt'
#         # message: 'ffff'
#         sigv4:
#           region: 'us-west-2'
#           access_key: 'AKIAXWP4LQRD4EA26UGL'
#           secret_key: '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'
#           profile: 'arn:aws:iam::529347085383:user/grafana'
#           # [ role_arn: <string> ]
#         attributes:
#           key: 'somekey'
#           value: 'somevalue'          


# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     equal: ['alertname', 'dev', 'instance']

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: webhook-receiver

receivers:
  # In this example we're not going to send any notification out of Alertmanager.
  - name: 'webhook-receiver'
    webhook_configs:
      - url: 'https://niceonline.webhook.office.com/webhookb2/47aff577-86f0-44e5-b411-236f60ea195e@7123dabd-0e87-4da9-9cb9-b7ec82011aad/IncomingWebhook/8bb082fd6f2a49cdaac5220bdd216087/5b3aa88d-b65b-4fdd-a543-b6124bfc98f8'

# # Global settings
# global:
#   resolve_timeout: 5m  # Maximum time to wait for an alert to resolve

# # Routing configuration
# route:
#   group_by: ['alertname']  # Group alerts by their name
#   group_wait: 30s          # Wait time before grouping alerts
#   group_interval: 5m       # Interval for grouping alerts
#   repeat_interval: 1h      # Interval for repeating notifications
#   receiver: 'webhook-receiver'  # Default receiver for alerts

# # Receiver configuration
# receivers:
#   - name: 'webhook-receiver'
#     webhook_configs:
#       - url: 'https://your-webhook-endpoint.com'  # Replace with your actual webhook URL
#         send_resolved: true  # Send resolved alerts as well

# # Inhibition rules
# inhibit_rules:
#   - source_match:
#       alertname: 'HighCPUUsage'  # Suppress related alerts while this one is active
#     target_match_re:
#       alertname: '.*'  # Match any other alert name

# # Additional route for the specific alert
# route:
#   routes:
#     - match:
#         alertname: 'HighCPUUsage'  # Match alerts with this name
#       receiver: 'webhook-receiver'  # Send to the webhook receiver
#       continue: true  # Continue processing other routes