receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        cors:
          allowed_origins:
          - http://*
          - https://*
        endpoint: 0.0.0.0:4318
processors:
  batch:
exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    #tls:
    #  insecure: true
    headers:
      X-Scope-OrgID: "anonymous"
  #prometheusremotewrite:
  #  endpoint: http://prometheus:9090/api/v1/write
  prometheusremotewrite/mimir:
    endpoint: "http://mimir:9009/api/v1/push"
    headers:
      X-Scope-OrgID: "anonymous"
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite/mimir]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
  telemetry:
    logs:
    metrics:
      address: 0.0.0.0:8888